---
- name: Install Apache Web Server
  become: yes
  package:
    name: apache2
    state: present

- name: Start Apache Service
  become: yes
  service:
    name: apache2
    state: started
    enabled: yes

